const fs = require('fs');

const layoutPath = 'src/app/layout.tsx';
let layoutCode = fs.readFileSync(layoutPath, 'utf8');

layoutCode = layoutCode.replace(/title: "Uyku Çizelgesi"/, 'title: "Sunrise Sleep Planner"');
layoutCode = layoutCode.replace(/title: "Create Next App"/, 'title: "Sunrise Sleep Planner"');
layoutCode = layoutCode.replace(/description: "Generated by create next app"/, 'description: "Sunrise-focused sleep schedule generator"');

fs.writeFileSync(layoutPath, layoutCode);
console.log('Fixed metadata title');
